const actions = {
  // Requests
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  GET_PROJECTS_REQUEST: "GET_PROJECTS_REQUEST",
  GET_PROJECT_REQUEST: "GET_PROJECT_REQUEST",
  ADD_PROJECT_REQUEST: "ADD_PROJECT_REQUEST",
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  GET_COMMENTS_REQUEST: "GET_COMMENTS_REQUEST",
  GET_COMMENTS_BY_ID_REQUEST: "GET_COMMENTS_BY_ID_REQUEST",

  // Successes
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  GET_PROJECTS_SUCCESS: "GET_PROJECTS_SUCCESS",
  GET_PROJECT_SUCCESS: "GET_PROJECT_SUCCESS",
  ADD_PROJECT_SUCCESS: "ADD_PROJECT_SUCCESS",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
  GET_COMMENTS_BY_ID_SUCCESS: "GET_COMMENTS_BY_ID_SUCCESS",
  // Failures
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  GET_PROJECTS_FAILURE: "GET_PROJECTS_FAILURE",
  GET_PROJECT_FAILURE: "GET_PROJECT_FAILURE",
  ADD_PROJECT_FAILURE: "ADD_PROJECT_FAILURE",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",
  GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE",
  GET_COMMENTS_BY_ID_FAILURE: "GET_COMMENTS_BY_ID_FAILURE",
}

export default actions
